name = "golazo"
installCommand = "npm install"
startCommand = "npx serve public -c ../serve.json -l $PORT"
port = 3000
projectId = "proj_fiyacox1vrpj7wxl9a1t"
deploymentId = "dep_yoticn9mlo5p5rktxwjb0"
projectUrl = "https://golazo.pxxl.run"
deploymentUrl = "https://pxxl.app/dashboard/projects/proj_fiyacox1vrpj7wxl9a1t/deployments/dep_yoticn9mlo5p5rktxwjb0"
lastDeployedAt = "2026-07-25T12:34:59.389Z"
